name: buildx

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
    paths:
      - ".github/workflows/buildx.yml"
      - "grafana/**"
      - "assets/**"
      - "config/**"
      - "lib/**"
      - "priv/**"
      - "rel/**"
      - "mix.exs"
      - "mix.lock"
      - "entrypoint.sh"
      - "Dockerfile"
      - "VERSION"

jobs:
  teslamate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: teslamate/teslamate
          tags: |
            type=edge,
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.0
      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: teslamate
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  grafana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: teslamate/grafana
          tags: |
            type=edge,
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.0
      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: teslamate
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: grafana
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
